export const VIEW_NAV = 'VIEW_NAV'
export const VIEW_FOOT = 'VIEW_FOOT'
export const VIEW_LOADING = 'VIEW_LOADING'

export const UPDATE_HOME = 'UPDATE_HOME'
export const UPDATE_FOLLOW = 'UPDATE_FOLLOW'
export const UPDATE_RANK = 'UPDATE_RANK'
export const UPDATE_BANNER = 'UPDATE_BANNER'
export const UPDATE_RECOMMEND = 'UPDATE_RECOMMEND'
export const UPDATE_SPECIAL = 'UPDATE_SPECIAL'



export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_DETAIL = 'UPDATE_DETAIL'
